-- Rename the Khata register to Quick Orders.
--
-- Prisma's autogenerated diff for a model rename is DROP TABLE + CREATE TABLE,
-- which would delete every row. This file replaces that with plain RENAMEs, so
-- not a single row moves — Postgres just relabels the objects in place.
--
-- Nothing here touches data. It is safe to run on production.

-- ── table + enum type ────────────────────────────────────────────────────────
ALTER TABLE "KhataEntry" RENAME TO "QuickOrder";
ALTER TYPE  "KhataStatus" RENAME TO "QuickOrderStatus";

-- ── QuickOrder: primary key, foreign key, indexes ────────────────────────────
ALTER TABLE "QuickOrder" RENAME CONSTRAINT "KhataEntry_pkey" TO "QuickOrder_pkey";
ALTER TABLE "QuickOrder" RENAME CONSTRAINT "KhataEntry_createdById_fkey" TO "QuickOrder_createdById_fkey";

ALTER INDEX "KhataEntry_entryDate_idx"    RENAME TO "QuickOrder_entryDate_idx";
ALTER INDEX "KhataEntry_customerName_idx" RENAME TO "QuickOrder_customerName_idx";
ALTER INDEX "KhataEntry_status_idx"       RENAME TO "QuickOrder_status_idx";
ALTER INDEX "KhataEntry_customerId_idx"   RENAME TO "QuickOrder_customerId_idx";

-- ── Task: the link column and everything named after it ──────────────────────
ALTER TABLE "Task" RENAME COLUMN "khataEntryId" TO "quickOrderId";
ALTER TABLE "Task" RENAME CONSTRAINT "Task_khataEntryId_fkey" TO "Task_quickOrderId_fkey";

ALTER INDEX "Task_khataEntryId_key" RENAME TO "Task_quickOrderId_key";
ALTER INDEX "Task_khataEntryId_idx" RENAME TO "Task_quickOrderId_idx";

-- ── cosmetic: the PG17 named NOT NULL constraints ────────────────────────────
-- Prisma neither creates nor tracks these names, so leaving them alone would
-- work fine. They are renamed only so no object in the database still reads
-- "Khata". Purely labels — the NOT NULL rules themselves are unchanged.
ALTER TABLE "QuickOrder" RENAME CONSTRAINT "KhataEntry_id_not_null"            TO "QuickOrder_id_not_null";
ALTER TABLE "QuickOrder" RENAME CONSTRAINT "KhataEntry_customerName_not_null"  TO "QuickOrder_customerName_not_null";
ALTER TABLE "QuickOrder" RENAME CONSTRAINT "KhataEntry_customerPhone_not_null" TO "QuickOrder_customerPhone_not_null";
ALTER TABLE "QuickOrder" RENAME CONSTRAINT "KhataEntry_customerEmail_not_null" TO "QuickOrder_customerEmail_not_null";
ALTER TABLE "QuickOrder" RENAME CONSTRAINT "KhataEntry_workDetails_not_null"   TO "QuickOrder_workDetails_not_null";
ALTER TABLE "QuickOrder" RENAME CONSTRAINT "KhataEntry_items_not_null"         TO "QuickOrder_items_not_null";
ALTER TABLE "QuickOrder" RENAME CONSTRAINT "KhataEntry_description_not_null"   TO "QuickOrder_description_not_null";
ALTER TABLE "QuickOrder" RENAME CONSTRAINT "KhataEntry_amount_not_null"        TO "QuickOrder_amount_not_null";
ALTER TABLE "QuickOrder" RENAME CONSTRAINT "KhataEntry_advancePaid_not_null"   TO "QuickOrder_advancePaid_not_null";
ALTER TABLE "QuickOrder" RENAME CONSTRAINT "KhataEntry_paymentMethod_not_null" TO "QuickOrder_paymentMethod_not_null";
ALTER TABLE "QuickOrder" RENAME CONSTRAINT "KhataEntry_status_not_null"        TO "QuickOrder_status_not_null";
ALTER TABLE "QuickOrder" RENAME CONSTRAINT "KhataEntry_entryDate_not_null"     TO "QuickOrder_entryDate_not_null";
ALTER TABLE "QuickOrder" RENAME CONSTRAINT "KhataEntry_createdAt_not_null"     TO "QuickOrder_createdAt_not_null";
ALTER TABLE "QuickOrder" RENAME CONSTRAINT "KhataEntry_updatedAt_not_null"     TO "QuickOrder_updatedAt_not_null";